defaults:
  install_options: --no-ri --no-rdoc --source=http://gemcutter.org --source=http://gems.github.com --source=http://gem.pivotallabs.com
gems:
- name: saucelabs-adapter
  version: 0.7.2
- name: selenium-client
  version: 1.2.17
- name: webrat
  version: 0.6.0
