defaults:
  install_options: --no-ri --no-rdoc --source=http://gemcutter.org --source=http://gems.github.com --source=http://gems.pivotallabs.com
gems:
- name: rails
  version: 2.3.5
- name: saucelabs-adapter
  version: 0.8
- name: selenium-client
  version: 1.2.18
- name: webrat
  version: 0.6.0
- name: sqlite3-ruby
